version: '2'
services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-pro:latest
    container_name: artifactory
    ports:
     - 8081:8081
# Uncomment to use persistent storage
#   volumes:
#    - /data/artifactory:/var/opt/jfrog/artifactory
    environment:
# IMPORTANT: MUST enter a valid Artifactory license with ART_LICENSE or Artifactory will not start!
     - ART_LICENSE=
     - AUTO_GEN_REPOS=docker
    restart: always
  nginx:
    image: docker.bintray.io/jfrog/nginx-artifactory-pro:latest
    container_name: nginx
    ports:
     - 80:80
     - 443:443
    depends_on:
     - artifactory
    links:
     - artifactory
# Uncomment to use persistent storage
#   volumes:
#    - /data/nginx/log:/var/log/nginx
#    - /data/nginx/conf.d/pro:/etc/nginx/conf.d
#   # To use your own certificate, just put your .key and .pem files in /data/nginx/ssl before starting docker-compose
#    - /data/nginx/ssl:/etc/nginx/ssl
    environment:
     - ART_BASE_URL=http://artifactory:8081/artifactory
     - SSL=true
    restart: always
