kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: artifactory-node1-claim
  labels:
    group: artifactory-k8s-demo
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: artifactory-node2-claim
  labels:
    group: artifactory-k8s-demo
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: artifactory-extra-conf-claim
  labels:
    group: artifactory-k8s-demo
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Mi
