kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-claim
  labels:
    group: artifactory-k8s-demo
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
